# Generated by Django 6.0.2 on 2026-07-01 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troid_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=200)),
                ('module', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('warning', 'Warning')], default='success', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HeatmapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('weight', models.FloatField()),
                ('source_type', models.CharField(default='waste', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SegregationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=20)),
                ('total_bags', models.IntegerField()),
                ('total_weight_kg', models.FloatField()),
                ('non_usable_weight_kg', models.FloatField()),
                ('recyclable_weight_kg', models.FloatField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('mayorsoffice', "Mayor's Office"), ('spearhead', 'Spearhead'), ('barangay', 'Barangay')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('offline', 'Offline'), ('archived', 'Archived')], default='active', max_length=20)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('onleave', 'On Leave')], default='online', max_length=20)),
                ('availability', models.CharField(choices=[('assigned', 'Assigned'), ('available', 'Available'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('assigned_bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operators', to='troid_api.boat')),
            ],
        ),
        migrations.CreateModel(
            name='LandfillRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=20, unique=True)),
                ('barangay', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=20)),
                ('bags', models.IntegerField()),
                ('weight_kg', models.FloatField()),
                ('vehicle', models.CharField(max_length=20)),
                ('disposed_by', models.CharField(max_length=100)),
                ('bot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landfill_records', to='troid_api.boat')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landfill_records', to='troid_api.operator')),
            ],
        ),
        migrations.CreateModel(
            name='RecyclingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=20, unique=True)),
                ('barangay', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=20)),
                ('bags', models.IntegerField()),
                ('weight_kg', models.FloatField()),
                ('category', models.CharField(max_length=50)),
                ('buyer', models.CharField(max_length=100)),
                ('sold_at', models.CharField(max_length=20)),
                ('bot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recycling_records', to='troid_api.boat')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recycling_records', to='troid_api.operator')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=20, unique=True)),
                ('request_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('processing', 'Processing'), ('completed', 'Completed'), ('segregated', 'Segregated')], default='pending', max_length=20)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('requested_by_name', models.CharField(max_length=100)),
                ('requested_by_role', models.CharField(max_length=50)),
                ('requested_by_barangay', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('location_name', models.CharField(max_length=100)),
                ('barangay', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('letter_file_name', models.CharField(blank=True, max_length=100)),
                ('letter_size', models.CharField(blank=True, max_length=20)),
                ('bags', models.IntegerField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('non_usable_kg', models.FloatField(blank=True, null=True)),
                ('recyclable_kg', models.FloatField(blank=True, null=True)),
                ('bot_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='troid_api.boat')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='troid_api.operator')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=50)),
                ('photo_id', models.IntegerField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='troid_api.request')),
            ],
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('actor', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('state', models.CharField(default='done', max_length=20)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='troid_api.request')),
            ],
        ),
        migrations.CreateModel(
            name='DeploymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('available', 'Available'), ('maintenance', 'Maintenance'), ('none', 'None')], default='none', max_length=20)),
                ('label', models.CharField(default='Available', max_length=20)),
                ('zone', models.CharField(blank=True, max_length=100)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='troid_api.boat')),
            ],
            options={
                'unique_together': {('bot', 'day')},
            },
        ),
    ]
