# Generated by Django 6.0.3 on 2026-06-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troid_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('spearhead', 'Spearhead'), ('officemayor', 'Office Mayor')], max_length=20)),
                ('full_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
