# Generated by Django 6.0.2 on 2026-07-01 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troid_api', '0002_auditlog_heatmapdata_segregationrecord_user_operator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='bot_id',
            field=models.ForeignKey(blank=True, db_column='bot_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='troid_api.boat'),
        ),
    ]
