# Generated by Django 6.0.3 on 2026-06-29 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troid_api', '0003_barangay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('onleave', 'On Leave')], default='online', max_length=20)),
                ('availability', models.CharField(choices=[('Assigned', 'Assigned'), ('Available', 'Available'), ('Unavailable', 'Unavailable')], default='Available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CleanupRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=20)),
                ('media', models.FileField(blank=True, null=True, upload_to='cleanup_requests/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('scheduled', 'Scheduled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='troid_api.barangay')),
                ('spearhead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleanup_requests', to='troid_api.user')),
            ],
        ),
        migrations.AddField(
            model_name='boat',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boats', to='troid_api.operator'),
        ),
        migrations.CreateModel(
            name='ScheduledCleanup',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='troid_api.cleanuprequest')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledBot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='troid_api.boat')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_bots', to='troid_api.scheduledcleanup')),
            ],
        ),
    ]
