# Generated by Django 6.0.2 on 2026-07-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troid_api', '0003_alter_request_bot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('offline', 'Offline'), ('archived', 'Archived')], default='active', max_length=20),
        ),
    ]
