# Generated by Django 6.0.3 on 2026-07-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troid_api', '0004_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
