# Generated by Django 6.0.3 on 2026-07-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troid_api', '0005_boat_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
