# Generated by Django 6.0.3 on 2026-07-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troid_api', '0006_boat_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='available', max_length=20),
        ),
    ]
