# Generated by Django 6.0.3 on 2026-07-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troid_api', '0007_operator_status_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
