# Generated by Django 6.0.3 on 2026-07-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troid_api', '0008_operator_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='operator_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
