# Generated by Django 6.0.3 on 2026-07-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troid_api', '0009_operator_id_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='operator_id',
            field=models.CharField(default='OP-0001', max_length=10, unique=True),
        ),
    ]
