# Generated by Django 6.0.3 on 2026-07-04 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('troid_api', '0010_operator_id_not_null'),
        ('troid_api', '0011_request_optional_fields'),
    ]

    operations = [
    ]
