# Generated by Django 6.0.3 on 2026-07-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troid_api', '0012_merge_20260704_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='operator_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('mayorsoffice', "Mayor's Office"), ('spearhead', 'Spearhead'), ('barangay', 'Barangay'), ('trial', 'Trial')], max_length=20),
        ),
    ]
