# Generated by Django 6.0.3 on 2026-07-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troid_api', '0013_user_password_user_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_data',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('mayorsoffice', "Mayor's Office"), ('barangay', 'Barangay'), ('trial', 'Trial')], max_length=20),
        ),
    ]
