# Generated by Django 6.0.3 on 2026-07-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troid_api', '0014_photo_image_data_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('mayorsoffice', "Mayor's Office"), ('barangay', 'Barangay')], max_length=20),
        ),
    ]
