# Generated by Django 6.0.3 on 2026-07-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troid_api', '0015_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='requested_by_role',
            field=models.CharField(default='barangay', max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending_mayor_approval', 'Pending Mayor Approval'), ('pending_admin_approval', 'Pending Admin Approval'), ('approved', 'Approved'), ('declined', 'Declined'), ('processing', 'Processing'), ('completed', 'Completed'), ('segregated', 'Segregated')], default='pending_mayor_approval', max_length=30),
        ),
    ]
