# Generated by Django 6.0.3 on 2026-07-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troid_api', '0019_request_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
