# Generated by Django 6.0.3 on 2026-07-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troid_api', '0020_boat_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionevent',
            name='categories',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
