# Generated by Django 6.0.3 on 2026-07-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troid_api', '0021_detectionevent_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionevent',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='detectionevent',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
