# Generated by Django 6.0.3 on 2026-07-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troid_api', '0022_detectionevent_confidence_detectionevent_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='decline_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='statushistory',
            name='details',
            field=models.TextField(blank=True, default=''),
        ),
    ]
