# Generated by Django 6.0.3 on 2026-07-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troid_api', '0023_request_decline_reason_statushistory_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
