# Generated by Django 6.0.3 on 2026-07-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troid_api', '0024_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_token',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
