# Generated by Django 6.0.3 on 2026-08-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troid_api', '0025_user_session_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('barangay', models.CharField(blank=True, max_length=100)),
                ('submitted_by', models.CharField(blank=True, max_length=100)),
                ('points', models.JSONField(default=list)),
                ('closed', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('decline_reason', models.TextField(blank=True, default='')),
                ('reviewed_by', models.CharField(blank=True, default='', max_length=100)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('date_reviewed', models.DateTimeField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
    ]
