# Generated by Django 6.0.3 on 2026-08-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troid_api', '0026_collectionarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='parked_from_status',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending_mayor_approval', 'Pending Mayor Approval'), ('pending_admin_approval', 'Pending Admin Approval'), ('approved', 'Approved'), ('declined', 'Declined'), ('parked', 'Parked'), ('processing', 'Processing'), ('completed', 'Completed'), ('segregated', 'Segregated')], default='pending_mayor_approval', max_length=30),
        ),
    ]
