# Generated by Django 6.0.3 on 2026-08-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troid_api', '0027_request_parked_from_status_alter_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='preferred_date',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='request',
            name='preferred_time',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
