# Generated by Django 6.0.3 on 2026-08-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troid_api', '0028_request_preferred_date_request_preferred_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('mayorsoffice', "Mayor's Office"), ('barangay', 'Barangay'), ('ngo', 'NGO')], max_length=20),
        ),
    ]
