# Generated by Django 6.0.3 on 2026-08-13 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troid_api', '0030_add_notification_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentschedule',
            name='cleanup_type',
            field=models.CharField(choices=[('troid_supported', 'TROID Supported'), ('unsupported', 'Unsupported')], default='troid_supported', max_length=20),
        ),
        migrations.AddField(
            model_name='detectionevent',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detection_events', to='troid_api.request'),
        ),
        migrations.AddField(
            model_name='request',
            name='session_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='trash_categories',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='request',
            name='verification_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='request',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='verified_categories',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('approved', 'Approved'), ('rescheduled', 'Rescheduled'), ('report_filed', 'Report Filed'), ('verified', 'Verified')], max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending_mayor_approval', 'Pending Mayor Approval'), ('pending_admin_approval', 'Pending Admin Approval'), ('approved', 'Approved'), ('declined', 'Declined'), ('parked', 'Parked'), ('processing', 'Processing'), ('completed', 'Completed'), ('segregated', 'Segregated'), ('pending_verification', 'Pending Verification'), ('verified', 'Verified')], default='pending_mayor_approval', max_length=30),
        ),
    ]
