# Generated by Django 6.0.3 on 2026-08-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troid_api', '0031_trash_report_and_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionarea',
            name='color',
            field=models.CharField(blank=True, default='#1b4de4', max_length=7),
        ),
    ]
