# Generated by Django 6.0.3 on 2026-08-23 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troid_api', '0032_collectionarea_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='collection_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='troid_api.collectionarea'),
        ),
    ]
