# Generated by Django 6.0.3 on 2026-08-26 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troid_api', '0033_request_collection_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay', models.CharField(max_length=100)),
                ('total_bags', models.IntegerField()),
                ('window_days', models.IntegerField(default=30)),
                ('identified_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_day', models.CharField(blank=True, max_length=20)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='troid_api.boat')),
                ('deployment_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priority_areas', to='troid_api.deploymentschedule')),
            ],
        ),
    ]
