# Generated by Django 6.0.3 on 2026-08-31 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troid_api', '0034_priorityarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_profile', to='troid_api.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('mayorsoffice', "Mayor's Office"), ('barangay', 'Barangay'), ('ngo', 'NGO'), ('operator', 'Operator')], max_length=20),
        ),
    ]
