import { useState } from "react";
import {
  Calendar,
  MapPin,
  FileText,
  FileBarChart2,
  Bot,
  Locate,
  Target,
  Search,
  FileDown,
  Sheet,
  Printer,
  Clock,
  UserCircle2,
} from "lucide-react";

// --- Mock Data ---

// Daily waste collection trend data (bags collected per day)
const trend = [
  { day: "May 1", bags: 48 }, { day: "May 3", bags: 55 }, { day: "May 6", bags: 68 },
  { day: "May 8", bags: 70 }, { day: "May 11", bags: 52 }, { day: "May 13", bags: 60 },
  { day: "May 16", bags: 78 }, { day: "May 18", bags: 58 }, { day: "May 21", bags: 62 },
  { day: "May 23", bags: 65 }, { day: "May 26", bags: 88 }, { day: "May 28", bags: 80 },
  { day: "May 31", bags: 65 },
];

// Waste type distribution for the donut chart
const wasteTypes = [
  { name: "Plastic Packaging", value: 700, pct: 30, color: "#22C55E" },
  { name: "Food Wrappers", value: 520, pct: 22, color: "#F59E0B" },
  { name: "Mixed Waste", value: 420, pct: 18, color: "#A855F7" },
  { name: "Plastic Bottles", value: 450, pct: 19, color: "#3B82F6" },
  { name: "Others", value: 250, pct: 11, color: "#EF4444" },
];

// Collection summary table data
const collections = [
  { date: "May 31, 2024", zone: "Riverside Park (Zone A)", bags: 85, unit: "AQUA-01", operator: "Team Alpha" },
  { date: "May 31, 2024", zone: "Downtown Coast (Zone B)", bags: 120, unit: "AQUA-02", operator: "Team Bravo" },
  { date: "May 30, 2024", zone: "Westfield Drainage (Zone C)", bags: 65, unit: "AQUA-01", operator: "Team Alpha" },
  { date: "May 30, 2024", zone: "Mangrove Edge (Zone D)", bags: 90, unit: "AQUA-03", operator: "Team Charlie" },
  { date: "May 29, 2024", zone: "Under Pier Area (Zone A)", bags: 70, unit: "AQUA-02", operator: "Team Bravo" },
];

// KPI stat cards data
const stats = [
  { label: "Total Bags Collected", value: "2,340", suffix: "Bags", delta: "+12.5%", icon: FileBarChart2, tint: "bg-blue-50 text-blue-500" },
  { label: "Total Robot Deployments", value: "56", suffix: "", delta: "+8.3%", icon: Bot, tint: "bg-emerald-50 text-emerald-500" },
  { label: "Patrol Zones Covered", value: "18", suffix: "", delta: "+5.9%", icon: Locate, tint: "bg-violet-50 text-violet-500" },
  { label: "Waste Collection Hotspots Identified", value: "24", suffix: "", delta: "+14.3%", icon: Target, tint: "bg-amber-50 text-amber-500" },
];

// Report overview metadata
const overview = [
  { label: "Date Range", value: "May 1, 2024 – May 31, 2024", icon: Calendar },
  { label: "Coverage Area", value: "", icon: MapPin },
  { label: "Report Type", value: "Collection Report", icon: FileText },
  { label: "Generated On", value: "May 31, 2024 10:30 AM", icon: Clock },
  { label: "Generated By", value: "CENRO Admin", icon: UserCircle2 },
];

// --- Reusable Sub-components ---

// Reusable label/value field with an icon, used in report filters
const FieldSelect = ({ icon: Icon, label, value }) => (
  <div>
    <p className="text-xs font-semibold text-slate-500 mb-1.5">{label}</p>
    <button className="w-full flex items-center gap-2.5 bg-white border border-slate-200 rounded-xl px-4 py-2.5 text-sm font-medium text-slate-700 hover:border-slate-300 transition-colors">
      <Icon size={16} className="text-slate-400 shrink-0" />
      <span className="truncate">{value}</span>
      <svg className="ml-auto w-3.5 h-3.5 text-slate-400 shrink-0" viewBox="0 0 12 12" fill="none">
        <path d="M3 4.5L6 7.5L9 4.5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
      </svg>
    </button>
  </div>
);

// Line chart component that visualizes the daily bag collection trend over time
const TrendChart = ({ data }) => {
  const width = 600;
  const height = 220;
  const padX = 8;             // Horizontal padding inside the SVG
  const padTop = 12;          // Top padding for the chart area
  const padBottom = 24;       // Bottom padding for x-axis labels
  const max = Math.max(...data.map((d) => d.bags)) * 1.15; // Y-axis max with headroom

  // Calculate inner drawing area dimensions
  const innerW = width - padX * 2;
  const innerH = height - padTop - padBottom;
  const stepX = innerW / (data.length - 1);

  // Map data points to SVG coordinates
  const points = data.map((d, i) => ({
    x: padX + i * stepX,
    y: padTop + innerH - (d.bags / max) * innerH,
  }));

  // Build SVG path strings for the line and filled area beneath it
  const linePath = points.map((p, i) => `${i === 0 ? "M" : "L"}${p.x},${p.y}`).join(" ");
  const areaPath = `${linePath} L${points[points.length - 1].x},${padTop + innerH} L${points[0].x},${padTop + innerH} Z`;

  // Horizontal grid lines at 0%, 25%, 50%, 75%, and 100% of the chart height
  const gridLines = [0, 0.25, 0.5, 0.75, 1];

  return (
    <svg viewBox={`0 0 ${width} ${height}`} className="w-full h-[240px]" preserveAspectRatio="none">
      <defs>
        <linearGradient id="bagsFill" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0%" stopColor="#3B82F6" stopOpacity="0.18" />
          <stop offset="100%" stopColor="#3B82F6" stopOpacity="0" />
        </linearGradient>
      </defs>
      {gridLines.map((g) => (
        <line
          key={g}
          x1={padX}
          x2={width - padX}
          y1={padTop + innerH * g}
          y2={padTop + innerH * g}
          stroke="#F1F5F9"
          strokeWidth="1"
        />
      ))}
      {/* Filled area beneath the trend line */}
      <path d={areaPath} fill="url(#bagsFill)" />
      {/* Main trend line */}
      <path d={linePath} fill="none" stroke="#3B82F6" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" />
      {/* Data point markers */}
      {points.map((p, i) => (
        <circle key={i} cx={p.x} cy={p.y} r="3" fill="#3B82F6" />
      ))}
      {/* X-axis day labels - show every other label to avoid crowding */}
      {data.map((d, i) =>
        i % 2 === 0 ? (
          <text key={d.day} x={points[i].x} y={height - 6} fontSize="10" fill="#94A3B8" textAnchor="middle">
            {d.day}
          </text>
        ) : null
      )}
    </svg>
  );
};

// Donut chart component that breaks down waste collection by type
const DonutChart = ({ data }) => {
  const size = 140;
  const radius = 60;
  const stroke = 20;
  const circumference = 2 * Math.PI * radius;
  const total = data.reduce((sum, d) => sum + d.value, 0);
  let offsetSoFar = 0;

  return (
    <div className="relative w-[140px] h-[140px] shrink-0">
      <svg width={size} height={size} viewBox={`0 0 ${size} ${size}`} className="-rotate-90">
        {/* Rotate -90deg so the first segment starts at the top (12 o'clock position) */}
        {data.map((d) => {
          const fraction = d.value / total;
          const dash = fraction * circumference;             // Arc length for this segment
          const gap = circumference - dash;                  // Remaining circumference as gap
          const rotation = (offsetSoFar / total) * 360;      // Where this segment starts
          offsetSoFar += d.value;
          return (
            <circle
              key={d.name}
              cx={size / 2}
              cy={size / 2}
              r={radius}
              fill="none"
              stroke={d.color}
              strokeWidth={stroke}
              strokeDasharray={`${dash} ${gap}`}
              strokeLinecap="butt"
              transform={`rotate(${rotation} ${size / 2} ${size / 2})`}
            />
          );
        })}
      </svg>
      {/* Center label showing the total */}
      <div className="absolute inset-0 flex flex-col items-center justify-center">
        <span className="text-lg font-bold text-slate-900">{total.toLocaleString()}</span>
        <span className="text-[10px] font-semibold text-slate-400">Total Bags</span>
      </div>
    </div>
  );
};

// --- Main Reports Page Component ---
const barangays = ["Carlatan Creek", "Biday Creek", "San Fernando Creek"];

const Reports = () => {
  const [search, setSearch] = useState("");
  const [dateFrom, setDateFrom] = useState("");
  const [dateTo, setDateTo] = useState("");
  const [selectedBarangay, setSelectedBarangay] = useState("");

  return (
    <div className="animate-fade-in pb-12">
      {/* Page header with title and description */}
      <header className="mb-6">
        <h1 className="text-[28px] font-bold text-slate-900 tracking-tight leading-none">Report Generation</h1>
        <p className="text-slate-500 text-sm mt-1.5 font-medium">
          Generate and export reports of aquatic waste collection and deployment activities.
        </p>
      </header>

      {/* Filter bar: lets the user select date range and location before generating */}
      <div className="bg-white rounded-2xl border border-slate-100 shadow-[0_4px_20px_rgba(0,0,0,0.03)] p-6 mb-6">
        <div className="flex flex-col lg:flex-row gap-4 lg:items-end">
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 flex-1">
            {/* Date Range with calendar inputs */}
            <div>
              <p className="text-xs font-semibold text-slate-500 mb-1.5">Date Range</p>
              <div className="flex items-center gap-2">
                <div className="relative flex-1">
                  <Calendar size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400 pointer-events-none" />
                  <input
                    type="date"
                    value={dateFrom}
                    onChange={(e) => setDateFrom(e.target.value)}
                    className="w-full flex items-center gap-2.5 bg-white border border-slate-200 rounded-xl px-4 py-2.5 text-sm font-medium text-slate-700 hover:border-slate-300 transition-colors pl-9"
                    placeholder="From"
                  />
                </div>
                <span className="text-slate-400 text-sm shrink-0">to</span>
                <div className="relative flex-1">
                  <Calendar size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400 pointer-events-none" />
                  <input
                    type="date"
                    value={dateTo}
                    onChange={(e) => setDateTo(e.target.value)}
                    className="w-full flex items-center gap-2.5 bg-white border border-slate-200 rounded-xl px-4 py-2.5 text-sm font-medium text-slate-700 hover:border-slate-300 transition-colors pl-9"
                    placeholder="To"
                  />
                </div>
              </div>
            </div>
            {/* Barangay / Location select dropdown */}
            <div>
              <p className="text-xs font-semibold text-slate-500 mb-1.5">Barangay / Location</p>
              <div className="relative">
                <MapPin size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400 pointer-events-none" />
<select
                   value={selectedBarangay}
                   onChange={(e) => setSelectedBarangay(e.target.value)}
                   className="w-full flex items-center gap-2.5 bg-white border border-slate-200 rounded-xl px-4 py-2.5 text-sm font-medium text-slate-700 hover:border-slate-300 transition-colors appearance-none pl-9 pr-8"
                 >
                   <option value="" disabled>Select Barangay / Location</option>
                   {barangays.map((b) => (
                     <option key={b} value={b}>{b}</option>
                   ))}
                 </select>
                <svg className="absolute right-3 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-slate-400 pointer-events-none" viewBox="0 0 12 12" fill="none">
                  <path d="M3 4.5L6 7.5L9 4.5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                </svg>
              </div>
            </div>
            {/* Report Type (left as is) */}
            <FieldSelect icon={FileText} label="Report Type" value="Collection Report" />
          </div>
          <button className="flex items-center justify-center gap-2 bg-blue-600 hover:bg-blue-700 text-white font-semibold text-sm rounded-xl px-5 py-2.5 transition-colors shrink-0">
            <FileText size={16} />
            Generate Report
          </button>
        </div>
      </div>

      {/* KPI stat cards row showing high-level collection and deployment metrics */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5 mb-6">
        {stats.map(({ label, value, suffix, delta, icon: Icon, tint }) => (
          <div key={label} className="bg-white rounded-2xl border border-slate-100 shadow-[0_4px_20px_rgba(0,0,0,0.03)] p-5 flex gap-4">
            {/* Icon container with color tint */}
            <div className={`w-11 h-11 rounded-xl flex items-center justify-center shrink-0 ${tint}`}>
              <Icon size={20} />
            </div>
            <div className="min-w-0">
              <p className="text-xs font-semibold text-slate-500 leading-tight">{label}</p>
              <p className="mt-1 text-2xl font-bold text-slate-900 leading-none">
                {value} {suffix && <span className="text-sm font-semibold text-slate-400">{suffix}</span>}
              </p>
              {/* Month-over-month comparison delta */}
              <p className="mt-1.5 text-xs font-semibold text-emerald-500 flex items-center gap-0.5">
                <svg width="10" height="10" viewBox="0 0 10 10" fill="none"><path d="M5 1L9 6H1L5 1Z" fill="currentColor" /></svg>
                {delta} <span className="text-slate-400 font-medium">vs Apr 1 - Apr 30</span>
              </p>
            </div>
          </div>
        ))}
      </div>

      {/* Charts section: trend line + waste type donut chart side-by-side */}
      <div className="grid grid-cols-1 lg:grid-cols-[1.6fr_1fr] gap-5 mb-6">
        {/* Time-series line chart of daily bag collections */}
        <div className="bg-white rounded-2xl border border-slate-100 shadow-[0_4px_20px_rgba(0,0,0,0.03)] p-6">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-sm font-bold text-slate-900">Total Bags Collected Over Time</h2>
            <span className="text-xs font-semibold text-slate-500 bg-slate-50 border border-slate-200 rounded-lg px-3 py-1.5">Daily</span>
          </div>
          <TrendChart data={trend} />
        </div>

        {/* Donut chart breaking down total bags by waste type */}
        <div className="bg-white rounded-2xl border border-slate-100 shadow-[0_4px_20px_rgba(0,0,0,0.03)] p-6">
          <h2 className="text-sm font-bold text-slate-900 mb-4">
            Waste Collection Distribution <span className="text-slate-400 font-medium">(by Type of Waste)</span>
          </h2>
          <div className="flex items-center gap-4">
            <DonutChart data={wasteTypes} />
            {/* Legend listing each waste type with its count and percentage */}
            <ul className="flex-1 space-y-2.5 min-w-0">
              {wasteTypes.map((w) => (
                <li key={w.name} className="flex items-center gap-2 text-xs">
                  <span className="w-2 h-2 rounded-full shrink-0" style={{ backgroundColor: w.color }} />
                  <span className="text-slate-600 font-medium truncate flex-1">{w.name}</span>
                  <span className="text-slate-900 font-semibold shrink-0">{w.value} ({w.pct}%)</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>

      {/* Bottom section: collection summary table + report overview / export actions */}
      <div className="grid grid-cols-1 lg:grid-cols-[1.6fr_1fr] gap-5">
        {/* Collection summary table with search filtering by zone */}
        <div className="bg-white rounded-2xl border border-slate-100 shadow-[0_4px_20px_rgba(0,0,0,0.03)] p-6">
          <div className="flex items-center justify-between mb-4 gap-3">
            <h2 className="text-sm font-bold text-slate-900">Collection Summary</h2>
            <div className="relative">
              <Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
              <input
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                placeholder="Search..."
                className="pl-8 pr-3 py-2 text-xs bg-slate-50 border border-slate-200 rounded-lg w-40 focus:outline-none focus:ring-2 focus:ring-blue-100 focus:border-blue-300"
              />
            </div>
          </div>
          <div className="overflow-x-auto -mx-2">
            <table className="w-full text-sm">
              <thead>
                <tr className="text-left text-xs font-semibold text-slate-400 border-b border-slate-100">
                  <th className="py-2.5 px-2 font-semibold">Date</th>
                  <th className="py-2.5 px-2 font-semibold">Location / Zone</th>
                  <th className="py-2.5 px-2 font-semibold">Bags Collected</th>
                  <th className="py-2.5 px-2 font-semibold">Robot / Unit</th>
                  <th className="py-2.5 px-2 font-semibold">Operator</th>
                  <th className="py-2.5 px-2 font-semibold">Status</th>
                </tr>
              </thead>
              <tbody>
                {/* Filter rows by matching the search term against the zone name */}
                {collections
                  .filter((c) => c.zone.toLowerCase().includes(search.toLowerCase()))
                  .map((c, i) => (
                    <tr key={i} className="border-b border-slate-50 last:border-0">
                      <td className="py-3 px-2 text-slate-500 whitespace-nowrap">{c.date}</td>
                      <td className="py-3 px-2 text-slate-700 font-medium">{c.zone}</td>
                      <td className="py-3 px-2 text-slate-700">{c.bags} Bags</td>
                      <td className="py-3 px-2 text-slate-500">{c.unit}</td>
                      <td className="py-3 px-2 text-slate-500">{c.operator}</td>
                      <td className="py-3 px-2">
                        <span className="inline-flex items-center gap-1.5 text-emerald-600 bg-emerald-50 text-xs font-semibold px-2.5 py-1 rounded-full">
                          <span className="w-1.5 h-1.5 rounded-full bg-emerald-500" /> Completed
                        </span>
                      </td>
                    </tr>
                  ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Report overview summary and quick-export actions */}
        <div className="bg-white rounded-2xl border border-slate-100 shadow-[0_4px_20px_rgba(0,0,0,0.03)] p-6 flex flex-col">
          <h2 className="text-sm font-bold text-slate-900 mb-4">Report Overview</h2>
<ul className="space-y-3.5 flex-1">
             {overview.map(({ label, value, icon: Icon }) => {
               const displayValue = label === "Coverage Area" ? selectedBarangay || "All Areas" : value;
               return (
                 <li key={label} className="flex items-start gap-3 text-sm">
                   <Icon size={16} className="text-slate-400 mt-0.5 shrink-0" />
                   <span className="text-slate-500 w-28 shrink-0">{label}</span>
                   <span className="text-slate-800 font-semibold">{displayValue}</span>
                 </li>
               );
             })}
           </ul>
          {/* Quick export buttons for the generated report */}
          <div className="grid grid-cols-3 gap-2.5 mt-5">
            <button className="flex flex-col items-center gap-1.5 border border-slate-200 rounded-xl py-3 text-xs font-semibold text-slate-600 hover:bg-slate-50 transition-colors">
              <FileDown size={16} className="text-red-500" /> Export PDF
            </button>
            <button className="flex flex-col items-center gap-1.5 border border-slate-200 rounded-xl py-3 text-xs font-semibold text-slate-600 hover:bg-slate-50 transition-colors">
              <Sheet size={16} className="text-emerald-600" /> Export Excel
            </button>
            <button className="flex flex-col items-center gap-1.5 border border-slate-200 rounded-xl py-3 text-xs font-semibold text-slate-600 hover:bg-slate-50 transition-colors">
              <Printer size={16} className="text-slate-500" /> Print Report
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Reports;
